"""Add customer and mediafile models

Revision ID: bd5f1d82697b
Revises: f84ddd0a59b8
Create Date: 2025-10-18 10:50:00.489629

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "bd5f1d82697b"
down_revision: Union[str, Sequence[str], None] = "f84ddd0a59b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "full_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "phone_number", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True
        ),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("gender", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "skin_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column(
            "health_conditions", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customer_deleted_at"), "customer", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_customer_phone_number"), "customer", ["phone_number"], unique=True
    )
    op.create_index(op.f("ix_customer_user_id"), "customer", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_customer_user_id"), table_name="customer")
    op.drop_index(op.f("ix_customer_phone_number"), table_name="customer")
    op.drop_index(op.f("ix_customer_deleted_at"), table_name="customer")
    op.drop_table("customer")
    # ### end Alembic commands ###
