"""implementation-email

Revision ID: 1e8c2b6f3759
Revises: e6f6753dc11e
Create Date: 2025-10-16 20:44:57.593371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1e8c2b6f3759'
down_revision: Union[str, Sequence[str], None] = 'e6f6753dc11e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resetpasswordtoken', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.add_column('verificationtoken', sa.Column('expires_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verificationtoken', 'expires_at')
    op.drop_column('resetpasswordtoken', 'expires_at')
    # ### end Alembic commands ###
