"""Add customer and mediafile models

Revision ID: f84ddd0a59b8
Revises: 20251017_213000_4a1c2e3f5a7b
Create Date: 2025-10-18 10:47:18.879337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f84ddd0a59b8'
down_revision: Union[str, Sequence[str], None] = '20251017_213000_4a1c2e3f5a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('customer',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('user_id', sa.Integer(), nullable=True),
    # sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    # sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    # sa.Column('date_of_birth', sa.Date(), nullable=True),
    # sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    # sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    # sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    # sa.Column('skin_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    # sa.Column('health_conditions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    # sa.Column('is_active', sa.Boolean(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=False),
    # sa.Column('updated_at', sa.DateTime(), nullable=False),
    # sa.Column('deleted_at', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_customer_deleted_at'), 'customer', ['deleted_at'], unique=False)
    # op.create_index(op.f('ix_customer_phone_number'), 'customer', ['phone_number'], unique=True)
    # op.create_index(op.f('ix_customer_user_id'), 'customer', ['user_id'], unique=False)
    op.alter_column('mediafile', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('mediafile', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('mediafile_file_path_key', 'mediafile', type_='unique')
    op.drop_index('ix_mediafile_file_path', table_name='mediafile')
    op.create_index(op.f('ix_mediafile_file_path'), 'mediafile', ['file_path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mediafile_file_path'), table_name='mediafile')
    op.create_index(op.f('ix_mediafile_file_path'), 'mediafile', ['file_path'], unique=False)
    op.create_unique_constraint(op.f('mediafile_file_path_key'), 'mediafile', ['file_path'], postgresql_nulls_not_distinct=False)
    op.alter_column('mediafile', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('mediafile', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_customer_user_id'), table_name='customer')
    op.drop_index(op.f('ix_customer_phone_number'), table_name='customer')
    op.drop_index(op.f('ix_customer_deleted_at'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
